<div id="header-button">
		<ul>
			<li><a href="admin_page.php">Add Another</a></li>
			<li><a href="admin_add_painting.php">Add Painting</a></li>
			<li><a href="#">View Orders</a></li>
			<!--<li><a href="#">Edit Content</a></li>-->
			<li><a href="#">New Password</a></li>
			<li><a href="logout.php">Logout</a></li>
		</ul>
	</div>
<h1>The Dove Gallery</h1>
<h2>Affordable Original Paintings</h2>
